version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: vida-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: vida-rentals
    volumes:
      - mongodb_data:/data/db
    networks:
      - vida-network

  redis:
    image: redis:7
    container_name: vida-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - vida-network

  mongo-express:
    image: mongo-express:latest
    container_name: vida-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - vida-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  vida-network:
    driver: bridge