import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation keys and values
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.inventory': 'Inventory',
    'nav.rentals': 'Rentals',
    'nav.sellCar': 'Sell Car',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.reseller': 'Reseller Panel',

    // Hero Section
    'hero.title': 'Most Trusted Car Dealership',
    'hero.subtitle': 'in Guanacaste',
    'hero.description': 'Explore a Wide Selection of Quality Vehicles at Unbeatable Prices. Your trusted partner for premium cars in Costa Rica\'s beautiful Guanacaste province.',
    'hero.browseInventory': 'Browse Inventory',
    'hero.contactUs': 'Contact Us',
    'hero.vehiclesSold': 'Vehicles Sold',
    'hero.happyCustomers': 'Happy Customers',
    'hero.averageRating': 'Average Rating',

    // Featured Vehicles
    'featured.title': 'Our Vehicle Inventory',
    'featured.description': 'Discover our extensive collection of premium vehicles available for purchase or rental. Each vehicle is carefully inspected and comes with our quality guarantee.',
    'featured.filterBy': 'Filter by:',
    'featured.allVehicles': 'All Vehicles',
    'featured.forSale': 'For Sale',
    'featured.forRental': 'For Rental',
    'featured.sedans': 'Sedans',
    'featured.suvs': 'SUVs',
    'featured.trucks': 'Trucks',
    'featured.coupes': 'Coupes',
    'featured.view': 'View:',
    'featured.showing': 'Showing',
    'featured.of': 'of',
    'featured.vehicles': 'vehicles',
    'featured.noVehicles': 'No vehicles found matching your criteria.',
    'featured.showAll': 'Show All Vehicles',
    'featured.dontSee': 'Don\'t See What You\'re Looking For?',
    'featured.dealerNetwork': 'We have access to thousands of vehicles through our dealer network. Let us help you find the perfect vehicle for your needs.',
    'featured.requestVehicle': 'Request a Vehicle',

    // Rentals Page
    'rentals.title': 'Vehicle Rentals',
    'rentals.description': 'Rent premium vehicles for your business or leisure needs. Flexible terms and competitive rates.',
    'rentals.flexibleDuration': 'Flexible Duration',
    'rentals.flexibleDesc': 'Daily, weekly, or monthly rentals available',
    'rentals.competitiveRates': 'Competitive Rates',
    'rentals.competitiveDesc': 'Best prices in the market with no hidden fees',
    'rentals.easyBooking': 'Easy Booking',
    'rentals.easyBookingDesc': 'Simple online booking process',
    'rentals.checkAvailability': 'Check Vehicle Availability',
    'rentals.selectDates': 'Select your rental dates to see which vehicles are available',
    'rentals.pickupDate': 'Pickup Date',
    'rentals.returnDate': 'Return Date',
    'rentals.clearDates': 'Clear Dates',
    'rentals.rentalPeriod': 'Rental Period',
    'rentals.days': 'days',
    'rentals.checkingAvailability': 'Checking availability...',
    'rentals.available': 'available',
    'rentals.allRentalVehicles': 'All Rental Vehicles',
    'rentals.availableRentalVehicles': 'Available Rental Vehicles',
    'rentals.checkingAvailabilityTitle': 'Checking Availability...',
    'rentals.checkingAvailabilityDesc': 'Please wait while we check which vehicles are available.',
    'rentals.errorCheckingTitle': 'Error Checking Availability',
    'rentals.noVehiclesAvailable': 'No vehicles available',
    'rentals.noRentalVehicles': 'No rental vehicles found',
    'rentals.allRentedMessage': 'All vehicles are rented during the selected dates. Please try different dates.',
    'rentals.noRentalsMessage': 'We currently don\'t have any vehicles available for rental.',
    'rentals.viewAllVehicles': 'View All Vehicles',

    // Vehicle Card
    'vehicle.rent': 'Rent',
    'vehicle.buy': 'Buy',
    'vehicle.viewDetails': 'View Details',
    'vehicle.perDay': '/day',
    'vehicle.year': 'Year',
    'vehicle.mileage': 'Mileage',
    'vehicle.transmission': 'Transmission',
    'vehicle.fuelType': 'Fuel Type',

    // Footer
    'footer.description': 'Your trusted partner in automotive excellence for over 20 years. We provide premium vehicles, exceptional service, and financing solutions.',
    'footer.quickLinks': 'Quick Links',
    'footer.vehicleInventory': 'Vehicle Inventory',
    'footer.sellYourCar': 'Sell Your Car',
    'footer.aboutUs': 'About Us',
    'footer.ourServices': 'Our Services',
    'footer.newCarSales': 'New Car Sales',
    'footer.usedCarSales': 'Used Car Sales',
    'footer.vehicleRentals': 'Vehicle Rentals',
    'footer.financingLeasing': 'Financing & Leasing',
    'footer.serviceMaintenance': 'Service & Maintenance',
    'footer.partsAccessories': 'Parts & Accessories',
    'footer.contactInfo': 'Contact Info',
    'footer.allRightsReserved': 'All rights reserved.',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.cookiePolicy': 'Cookie Policy',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.name': 'Name',
    'common.message': 'Message',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.or': 'or',
    'common.and': 'and',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'common.selected': 'Selected',
    'common.clear': 'Clear',
    'common.reset': 'Reset',
    'common.apply': 'Apply',
    'common.show': 'Show',
    'common.hide': 'Hide',
    'common.more': 'More',
    'common.less': 'Less',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.amount': 'Amount',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.from': 'From',
    'common.to': 'To',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.description': 'Description',
    'common.details': 'Details',
    'common.notes': 'Notes',
    'common.optional': 'Optional',
    'common.required': 'Required',

    // Admin Panel
    'admin.dashboard': 'Dashboard',
    'admin.vehicleManagement': 'Vehicle Management',
    'admin.userManagement': 'User Management',
    'admin.bookingManagement': 'Booking Management',
    'admin.analytics': 'Analytics',
    'admin.settings': 'Settings',
    'admin.resellerManagement': 'Reseller Management',
    'admin.customerManagement': 'Customer Management',
    'admin.rentalManagement': 'Rental Management',
    'admin.reports': 'Reports',
    'admin.totalVehicles': 'Total Vehicles',
    'admin.totalBookings': 'Total Bookings',
    'admin.totalRevenue': 'Total Revenue',
    'admin.activeResellers': 'Active Resellers',
    'admin.addVehicle': 'Add Vehicle',
    'admin.editVehicle': 'Edit Vehicle',
    'admin.deleteVehicle': 'Delete Vehicle',
    'admin.vehicleList': 'Vehicle List',
    'admin.vehicleDetails': 'Vehicle Details',
    'admin.vehicleStatus': 'Vehicle Status',
    'admin.featuredVehicles': 'Featured Vehicles',
    'admin.exportData': 'Export Data',
    'admin.importData': 'Import Data',

    // Reseller Panel
    'reseller.dashboard': 'Reseller Dashboard',
    'reseller.dashboardTitle': 'Dashboard',
    'reseller.bookVehicles': 'Book Vehicles',
    'reseller.vehicleBooking': 'Vehicle Booking',
    'reseller.resellerPanel': 'Reseller Panel',
    'reseller.welcome': 'Welcome',
    'reseller.returnHome': 'Return to Home',
    'reseller.logout': 'Logout',
    'reseller.myBookings': 'My Bookings',
    'reseller.earnings': 'Earnings',
    'reseller.commission': 'Commission',
    'reseller.commissionRate': 'Your Commission Rate',
    'reseller.resellerCharge': 'Reseller Charge',
    'reseller.selectCharge': 'Select Reseller Charge',
    'reseller.customerInfo': 'Customer Information',
    'reseller.customerName': 'Customer Name',
    'reseller.customerEmail': 'Customer Email',
    'reseller.customerPhone': 'Customer Phone',
    'reseller.pickupTime': 'Pickup Time',
    'reseller.bookForCustomer': 'Book for Customer',
    'reseller.selectDatesToBook': 'Select Dates to Book',
    'reseller.checkAvailability': 'Check Vehicle Availability',
    'reseller.pricingBreakdown': 'Pricing Breakdown',
    'reseller.baseRate': 'Base Rate',
    'reseller.yourCommission': 'Your Commission',
    'reseller.yourCharge': 'Your Charge',
    'reseller.customerPays': 'Customer Pays',
    'reseller.clientPays': 'Client Pays',
    'reseller.yourEarnings': 'Your Earnings',
    'reseller.totalEarnings': 'Your Total Earnings',
    'reseller.confirmBooking': 'Confirm Booking',
    'reseller.bookingSuccess': 'Booking submitted successfully!',
    'reseller.bookingError': 'Failed to submit booking. Please try again.',
    'reseller.paymentMethod': 'Payment Method',
    'reseller.cash': 'Cash',
    'reseller.creditCard': 'Credit Card',
    'reseller.cashPrice': 'Cash Price',
    'reseller.creditCardPrice': 'Credit Card Price',
    'reseller.evaCharge': 'EVA Charge (14%)',
    'reseller.selectPaymentMethod': 'Select Payment Method',
    'reseller.viewDetails': 'View Details',
    'reseller.vehicleDetails': 'Vehicle Details',
    'reseller.bookThisVehicle': 'Book This Vehicle',
    'reseller.totalSales': 'Total Sales',
    'reseller.activeCustomers': 'Active Customers',
    'reseller.commissionEarned': 'Commission Earned',
    'reseller.recentBookings': 'Recent Bookings',
    'reseller.loadingDashboard': 'Loading dashboard...',
    'reseller.errorLoadingDashboard': 'Error Loading Dashboard',
    'reseller.unableToLoadDashboard': 'Unable to load dashboard data',
    'reseller.retry': 'Retry',
    'reseller.welcomeBack': 'Welcome back',
    'reseller.noBookingsYet': 'No bookings yet',
    'reseller.startBooking': 'Start booking vehicles to see them here',
    'reseller.customer': 'Customer',
    'reseller.status': 'Status',
    'reseller.viewAllBookings': 'View All Bookings',
    'reseller.dashboardDescription': 'Here\'s what\'s happening with your reseller account today.',
    'reseller.recentActivity': 'Recent Activity',
    'reseller.noRecentActivity': 'No recent activity',
    'reseller.upcomingTasks': 'Upcoming Tasks',

    // Vehicle Details
    'vehicle.specifications': 'Specifications',
    'vehicle.features': 'Features',
    'vehicle.equipment': 'Equipment',
    'vehicle.condition': 'Condition',
    'vehicle.exteriorColor': 'Exterior Color',
    'vehicle.interiorColor': 'Interior Color',
    'vehicle.engineType': 'Engine Type',
    'vehicle.horsepower': 'Horsepower',
    'vehicle.drivetrain': 'Drivetrain',
    'vehicle.towingCapacity': 'Towing Capacity',
    'vehicle.location': 'Location',
    'vehicle.available': 'Available',
    'vehicle.notAvailable': 'Not Available',
    'vehicle.bookNow': 'Book Now',
    'vehicle.scheduleTestDrive': 'Schedule Test Drive',
    'vehicle.contactDealer': 'Contact Dealer',
    'vehicle.similarVehicles': 'Similar Vehicles',
    'vehicle.shareVehicle': 'Share Vehicle',
    'vehicle.saveVehicle': 'Save Vehicle',
    'vehicle.printDetails': 'Print Details',

    // Forms
    'form.fillRequiredFields': 'Please fill in all required fields',
    'form.invalidEmail': 'Please enter a valid email address',
    'form.invalidPhone': 'Please enter a valid phone number',
    'form.selectDate': 'Please select a date',
    'form.selectTime': 'Please select a time',
    'form.enterName': 'Please enter your name',
    'form.enterEmail': 'Please enter your email',
    'form.enterPhone': 'Please enter your phone number',
    'form.enterMessage': 'Please enter your message',
    'form.agreeToTerms': 'Please agree to the terms and conditions',
    'form.submitSuccess': 'Form submitted successfully!',
    'form.submitError': 'Error submitting form. Please try again.',

    // Booking
    'booking.pickupDate': 'Pickup Date',
    'booking.returnDate': 'Return Date',
    'booking.rentalPeriod': 'Rental Period',
    'booking.totalDays': 'Total Days',
    'booking.dailyRate': 'Daily Rate',
    'booking.totalCost': 'Total Cost',
    'booking.bookingDetails': 'Booking Details',
    'booking.bookingConfirmation': 'Booking Confirmation',
    'booking.bookingReference': 'Booking Reference',
    'booking.paymentDetails': 'Payment Details',
    'booking.termsAndConditions': 'Terms and Conditions',
    'booking.cancellationPolicy': 'Cancellation Policy',
    'booking.modifyBooking': 'Modify Booking',
    'booking.cancelBooking': 'Cancel Booking',

    // Inventory Page
    'inventory.title': 'Vehicle Inventory',
    'inventory.searchPlaceholder': 'Search vehicles...',
    'inventory.filterByType': 'Filter by Type',
    'inventory.filterByCategory': 'Filter by Category',
    'inventory.filterByPrice': 'Filter by Price',
    'inventory.sortBy': 'Sort By',
    'inventory.priceRange': 'Price Range',
    'inventory.yearRange': 'Year Range',
    'inventory.mileageRange': 'Mileage Range',
    'inventory.showingResults': 'Showing {count} results',
    'inventory.noResults': 'No vehicles found matching your criteria',
    'inventory.clearFilters': 'Clear Filters',
    'inventory.compareVehicles': 'Compare Vehicles',
    'inventory.gridView': 'Grid View',
    'inventory.listView': 'List View',

    // About Page
    'about.title': 'About Vida Motors',
    'about.ourStory': 'Our Story',
    'about.mission': 'Our Mission',
    'about.vision': 'Our Vision',
    'about.values': 'Our Values',
    'about.team': 'Our Team',
    'about.whyChooseUs': 'Why Choose Us',
    'about.experience': 'Years of Experience',
    'about.commitment': 'Commitment to Quality',
    'about.customerService': 'Exceptional Customer Service',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.getInTouch': 'Get In Touch',
    'contact.visitUs': 'Visit Us',
    'contact.callUs': 'Call Us',
    'contact.emailUs': 'Email Us',
    'contact.businessHours': 'Business Hours',
    'contact.mondayFriday': 'Monday - Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.closed': 'Closed',
    'contact.sendMessage': 'Send Message',
    'contact.findUs': 'Find Us',
    'contact.directions': 'Get Directions',

    // Sell Car Page
    'sellCar.title': 'Sell Your Car',
    'sellCar.description': 'Get the best value for your vehicle',
    'sellCar.vehicleInfo': 'Vehicle Information',
    'sellCar.personalInfo': 'Personal Information',
    'sellCar.uploadPhotos': 'Upload Photos',
    'sellCar.getQuote': 'Get Quote',
    'sellCar.instantOffer': 'Get an Instant Offer',
    'sellCar.fairPrice': 'Fair Market Price',
    'sellCar.quickProcess': 'Quick & Easy Process',

    // Login/Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.emailAddress': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.rememberMe': 'Remember Me',
    'auth.loginSuccess': 'Login successful!',
    'auth.loginError': 'Invalid email or password',
    'auth.logoutSuccess': 'Logged out successfully',
    'auth.unauthorized': 'Unauthorized access',

    // Errors
    'error.pageNotFound': 'Page Not Found',
    'error.somethingWentWrong': 'Something Went Wrong',
    'error.tryAgain': 'Please Try Again',
    'error.goHome': 'Go to Homepage',
    'error.contactSupport': 'Contact Support',

    // Success Messages
    'success.saved': 'Saved successfully',
    'success.updated': 'Updated successfully',
    'success.deleted': 'Deleted successfully',
    'success.sent': 'Sent successfully',
    'success.booked': 'Booked successfully',
    'success.cancelled': 'Cancelled successfully'
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.inventory': 'Inventario',
    'nav.rentals': 'Alquileres',
    'nav.sellCar': 'Vender Auto',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'nav.admin': 'Administrador',
    'nav.reseller': 'Panel de Revendedor',

    // Hero Section
    'hero.title': 'Concesionario de Autos Más Confiable',
    'hero.subtitle': 'en Guanacaste',
    'hero.description': 'Explora una Amplia Selección de Vehículos de Calidad a Precios Inmejorables. Tu socio de confianza para autos premium en la hermosa provincia de Guanacaste, Costa Rica.',
    'hero.browseInventory': 'Ver Inventario',
    'hero.contactUs': 'Contáctanos',
    'hero.vehiclesSold': 'Vehículos Vendidos',
    'hero.happyCustomers': 'Clientes Satisfechos',
    'hero.averageRating': 'Calificación Promedio',

    // Featured Vehicles
    'featured.title': 'Nuestro Inventario de Vehículos',
    'featured.description': 'Descubre nuestra extensa colección de vehículos premium disponibles para compra o alquiler. Cada vehículo es cuidadosamente inspeccionado y viene con nuestra garantía de calidad.',
    'featured.filterBy': 'Filtrar por:',
    'featured.allVehicles': 'Todos los Vehículos',
    'featured.forSale': 'En Venta',
    'featured.forRental': 'Para Alquiler',
    'featured.sedans': 'Sedanes',
    'featured.suvs': 'SUVs',
    'featured.trucks': 'Camionetas',
    'featured.coupes': 'Cupés',
    'featured.view': 'Vista:',
    'featured.showing': 'Mostrando',
    'featured.of': 'de',
    'featured.vehicles': 'vehículos',
    'featured.noVehicles': 'No se encontraron vehículos que coincidan con sus criterios.',
    'featured.showAll': 'Mostrar Todos los Vehículos',
    'featured.dontSee': '¿No Ves Lo Que Buscas?',
    'featured.dealerNetwork': 'Tenemos acceso a miles de vehículos a través de nuestra red de concesionarios. Permítenos ayudarte a encontrar el vehículo perfecto para tus necesidades.',
    'featured.requestVehicle': 'Solicitar un Vehículo',

    // Rentals Page
    'rentals.title': 'Alquiler de Vehículos',
    'rentals.description': 'Alquila vehículos premium para tus necesidades comerciales o de ocio. Términos flexibles y tarifas competitivas.',
    'rentals.flexibleDuration': 'Duración Flexible',
    'rentals.flexibleDesc': 'Alquileres diarios, semanales o mensuales disponibles',
    'rentals.competitiveRates': 'Tarifas Competitivas',
    'rentals.competitiveDesc': 'Los mejores precios del mercado sin comisiones ocultas',
    'rentals.easyBooking': 'Reserva Fácil',
    'rentals.easyBookingDesc': 'Proceso de reserva en línea simple',
    'rentals.checkAvailability': 'Verificar Disponibilidad de Vehículos',
    'rentals.selectDates': 'Selecciona las fechas de alquiler para ver qué vehículos están disponibles',
    'rentals.pickupDate': 'Fecha de Recogida',
    'rentals.returnDate': 'Fecha de Devolución',
    'rentals.clearDates': 'Limpiar Fechas',
    'rentals.rentalPeriod': 'Período de Alquiler',
    'rentals.days': 'días',
    'rentals.checkingAvailability': 'Verificando disponibilidad...',
    'rentals.available': 'disponible',
    'rentals.allRentalVehicles': 'Todos los Vehículos de Alquiler',
    'rentals.availableRentalVehicles': 'Vehículos de Alquiler Disponibles',
    'rentals.checkingAvailabilityTitle': 'Verificando Disponibilidad...',
    'rentals.checkingAvailabilityDesc': 'Por favor espera mientras verificamos qué vehículos están disponibles.',
    'rentals.errorCheckingTitle': 'Error al Verificar Disponibilidad',
    'rentals.noVehiclesAvailable': 'No hay vehículos disponibles',
    'rentals.noRentalVehicles': 'No se encontraron vehículos de alquiler',
    'rentals.allRentedMessage': 'Todos los vehículos están alquilados durante las fechas seleccionadas. Por favor intenta con fechas diferentes.',
    'rentals.noRentalsMessage': 'Actualmente no tenemos vehículos disponibles para alquiler.',
    'rentals.viewAllVehicles': 'Ver Todos los Vehículos',

    // Vehicle Card
    'vehicle.rent': 'Alquilar',
    'vehicle.buy': 'Comprar',
    'vehicle.viewDetails': 'Ver Detalles',
    'vehicle.perDay': '/día',
    'vehicle.year': 'Año',
    'vehicle.mileage': 'Kilometraje',
    'vehicle.transmission': 'Transmisión',
    'vehicle.fuelType': 'Tipo de Combustible',

    // Footer
    'footer.description': 'Tu socio de confianza en excelencia automotriz por más de 20 años. Proporcionamos vehículos premium, servicio excepcional y soluciones de financiamiento.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.vehicleInventory': 'Inventario de Vehículos',
    'footer.sellYourCar': 'Vende Tu Auto',
    'footer.aboutUs': 'Acerca de Nosotros',
    'footer.ourServices': 'Nuestros Servicios',
    'footer.newCarSales': 'Venta de Autos Nuevos',
    'footer.usedCarSales': 'Venta de Autos Usados',
    'footer.vehicleRentals': 'Alquiler de Vehículos',
    'footer.financingLeasing': 'Financiamiento y Arrendamiento',
    'footer.serviceMaintenance': 'Servicio y Mantenimiento',
    'footer.partsAccessories': 'Partes y Accesorios',
    'footer.contactInfo': 'Información de Contacto',
    'footer.allRightsReserved': 'Todos los derechos reservados.',
    'footer.privacyPolicy': 'Política de Privacidad',
    'footer.termsOfService': 'Términos de Servicio',
    'footer.cookiePolicy': 'Política de Cookies',

    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.close': 'Cerrar',
    'common.email': 'Correo Electrónico',
    'common.phone': 'Teléfono',
    'common.name': 'Nombre',
    'common.message': 'Mensaje',
    'common.submit': 'Enviar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Agregar',
    'common.view': 'Ver',
    'common.download': 'Descargar',
    'common.upload': 'Subir',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.or': 'o',
    'common.and': 'y',
    'common.all': 'Todos',
    'common.none': 'Ninguno',
    'common.select': 'Seleccionar',
    'common.selected': 'Seleccionado',
    'common.clear': 'Limpiar',
    'common.reset': 'Restablecer',
    'common.apply': 'Aplicar',
    'common.show': 'Mostrar',
    'common.hide': 'Ocultar',
    'common.more': 'Más',
    'common.less': 'Menos',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.price': 'Precio',
    'common.quantity': 'Cantidad',
    'common.amount': 'Monto',
    'common.date': 'Fecha',
    'common.time': 'Hora',
    'common.from': 'Desde',
    'common.to': 'Hasta',
    'common.status': 'Estado',
    'common.actions': 'Acciones',
    'common.description': 'Descripción',
    'common.details': 'Detalles',
    'common.notes': 'Notas',
    'common.optional': 'Opcional',
    'common.required': 'Requerido',

    // Admin Panel
    'admin.dashboard': 'Panel de Control',
    'admin.vehicleManagement': 'Gestión de Vehículos',
    'admin.userManagement': 'Gestión de Usuarios',
    'admin.bookingManagement': 'Gestión de Reservas',
    'admin.analytics': 'Análisis',
    'admin.settings': 'Configuración',
    'admin.resellerManagement': 'Gestión de Revendedores',
    'admin.customerManagement': 'Gestión de Clientes',
    'admin.rentalManagement': 'Gestión de Alquileres',
    'admin.reports': 'Informes',
    'admin.totalVehicles': 'Total de Vehículos',
    'admin.totalBookings': 'Total de Reservas',
    'admin.totalRevenue': 'Ingresos Totales',
    'admin.activeResellers': 'Revendedores Activos',
    'admin.addVehicle': 'Agregar Vehículo',
    'admin.editVehicle': 'Editar Vehículo',
    'admin.deleteVehicle': 'Eliminar Vehículo',
    'admin.vehicleList': 'Lista de Vehículos',
    'admin.vehicleDetails': 'Detalles del Vehículo',
    'admin.vehicleStatus': 'Estado del Vehículo',
    'admin.featuredVehicles': 'Vehículos Destacados',
    'admin.exportData': 'Exportar Datos',
    'admin.importData': 'Importar Datos',

    // Reseller Panel
    'reseller.dashboard': 'Panel de Revendedor',
    'reseller.dashboardTitle': 'Panel',
    'reseller.bookVehicles': 'Reservar Vehículos',
    'reseller.vehicleBooking': 'Reserva de Vehículos',
    'reseller.resellerPanel': 'Panel de Revendedor',
    'reseller.welcome': 'Bienvenido',
    'reseller.returnHome': 'Volver al Inicio',
    'reseller.logout': 'Cerrar Sesión',
    'reseller.myBookings': 'Mis Reservas',
    'reseller.earnings': 'Ganancias',
    'reseller.commission': 'Comisión',
    'reseller.commissionRate': 'Tu Tasa de Comisión',
    'reseller.resellerCharge': 'Cargo del Revendedor',
    'reseller.selectCharge': 'Seleccionar Cargo del Revendedor',
    'reseller.customerInfo': 'Información del Cliente',
    'reseller.customerName': 'Nombre del Cliente',
    'reseller.customerEmail': 'Correo del Cliente',
    'reseller.customerPhone': 'Teléfono del Cliente',
    'reseller.pickupTime': 'Hora de Recogida',
    'reseller.bookForCustomer': 'Reservar para Cliente',
    'reseller.selectDatesToBook': 'Selecciona Fechas para Reservar',
    'reseller.checkAvailability': 'Verificar Disponibilidad de Vehículos',
    'reseller.pricingBreakdown': 'Desglose de Precios',
    'reseller.baseRate': 'Tarifa Base',
    'reseller.yourCommission': 'Tu Comisión',
    'reseller.yourCharge': 'Tu Cargo',
    'reseller.customerPays': 'El Cliente Paga',
    'reseller.clientPays': 'El Cliente Paga',
    'reseller.yourEarnings': 'Tus Ganancias',
    'reseller.totalEarnings': 'Tus Ganancias Totales',
    'reseller.confirmBooking': 'Confirmar Reserva',
    'reseller.bookingSuccess': '¡Reserva enviada exitosamente!',
    'reseller.bookingError': 'Error al enviar la reserva. Por favor intenta de nuevo.',
    'reseller.paymentMethod': 'Método de Pago',
    'reseller.cash': 'Efectivo',
    'reseller.creditCard': 'Tarjeta de Crédito',
    'reseller.cashPrice': 'Precio en Efectivo',
    'reseller.creditCardPrice': 'Precio con Tarjeta',
    'reseller.evaCharge': 'Cargo EVA (14%)',
    'reseller.selectPaymentMethod': 'Seleccionar Método de Pago',
    'reseller.viewDetails': 'Ver Detalles',
    'reseller.vehicleDetails': 'Detalles del Vehículo',
    'reseller.bookThisVehicle': 'Reservar Este Vehículo',
    'reseller.totalSales': 'Ventas Totales',
    'reseller.activeCustomers': 'Clientes Activos',
    'reseller.commissionEarned': 'Comisión Ganada',
    'reseller.recentBookings': 'Reservas Recientes',
    'reseller.loadingDashboard': 'Cargando panel...',
    'reseller.errorLoadingDashboard': 'Error al Cargar el Panel',
    'reseller.unableToLoadDashboard': 'No se pudo cargar los datos del panel',
    'reseller.retry': 'Reintentar',
    'reseller.welcomeBack': 'Bienvenido de vuelta',
    'reseller.noBookingsYet': 'Sin reservas aún',
    'reseller.startBooking': 'Comienza a reservar vehículos para verlos aquí',
    'reseller.customer': 'Cliente',
    'reseller.status': 'Estado',
    'reseller.viewAllBookings': 'Ver Todas las Reservas',
    'reseller.dashboardDescription': 'Esto es lo que está sucediendo con tu cuenta de revendedor hoy.',
    'reseller.recentActivity': 'Actividad Reciente',
    'reseller.noRecentActivity': 'Sin actividad reciente',
    'reseller.upcomingTasks': 'Tareas Próximas',

    // Vehicle Details
    'vehicle.specifications': 'Especificaciones',
    'vehicle.features': 'Características',
    'vehicle.equipment': 'Equipamiento',
    'vehicle.condition': 'Condición',
    'vehicle.exteriorColor': 'Color Exterior',
    'vehicle.interiorColor': 'Color Interior',
    'vehicle.engineType': 'Tipo de Motor',
    'vehicle.horsepower': 'Caballos de Fuerza',
    'vehicle.drivetrain': 'Tracción',
    'vehicle.towingCapacity': 'Capacidad de Remolque',
    'vehicle.location': 'Ubicación',
    'vehicle.available': 'Disponible',
    'vehicle.notAvailable': 'No Disponible',
    'vehicle.bookNow': 'Reservar Ahora',
    'vehicle.scheduleTestDrive': 'Programar Prueba de Manejo',
    'vehicle.contactDealer': 'Contactar Distribuidor',
    'vehicle.similarVehicles': 'Vehículos Similares',
    'vehicle.shareVehicle': 'Compartir Vehículo',
    'vehicle.saveVehicle': 'Guardar Vehículo',
    'vehicle.printDetails': 'Imprimir Detalles',

    // Forms
    'form.fillRequiredFields': 'Por favor complete todos los campos requeridos',
    'form.invalidEmail': 'Por favor ingrese un correo electrónico válido',
    'form.invalidPhone': 'Por favor ingrese un número de teléfono válido',
    'form.selectDate': 'Por favor seleccione una fecha',
    'form.selectTime': 'Por favor seleccione una hora',
    'form.enterName': 'Por favor ingrese su nombre',
    'form.enterEmail': 'Por favor ingrese su correo electrónico',
    'form.enterPhone': 'Por favor ingrese su número de teléfono',
    'form.enterMessage': 'Por favor ingrese su mensaje',
    'form.agreeToTerms': 'Por favor acepte los términos y condiciones',
    'form.submitSuccess': '¡Formulario enviado exitosamente!',
    'form.submitError': 'Error al enviar el formulario. Por favor intente de nuevo.',

    // Booking
    'booking.pickupDate': 'Fecha de Recogida',
    'booking.returnDate': 'Fecha de Devolución',
    'booking.rentalPeriod': 'Período de Alquiler',
    'booking.totalDays': 'Total de Días',
    'booking.dailyRate': 'Tarifa Diaria',
    'booking.totalCost': 'Costo Total',
    'booking.bookingDetails': 'Detalles de la Reserva',
    'booking.bookingConfirmation': 'Confirmación de Reserva',
    'booking.bookingReference': 'Referencia de Reserva',
    'booking.paymentDetails': 'Detalles de Pago',
    'booking.termsAndConditions': 'Términos y Condiciones',
    'booking.cancellationPolicy': 'Política de Cancelación',
    'booking.modifyBooking': 'Modificar Reserva',
    'booking.cancelBooking': 'Cancelar Reserva',

    // Inventory Page
    'inventory.title': 'Inventario de Vehículos',
    'inventory.searchPlaceholder': 'Buscar vehículos...',
    'inventory.filterByType': 'Filtrar por Tipo',
    'inventory.filterByCategory': 'Filtrar por Categoría',
    'inventory.filterByPrice': 'Filtrar por Precio',
    'inventory.sortBy': 'Ordenar Por',
    'inventory.priceRange': 'Rango de Precio',
    'inventory.yearRange': 'Rango de Año',
    'inventory.mileageRange': 'Rango de Kilometraje',
    'inventory.showingResults': 'Mostrando {count} resultados',
    'inventory.noResults': 'No se encontraron vehículos que coincidan con sus criterios',
    'inventory.clearFilters': 'Limpiar Filtros',
    'inventory.compareVehicles': 'Comparar Vehículos',
    'inventory.gridView': 'Vista de Cuadrícula',
    'inventory.listView': 'Vista de Lista',

    // About Page
    'about.title': 'Acerca de Vida Motors',
    'about.ourStory': 'Nuestra Historia',
    'about.mission': 'Nuestra Misión',
    'about.vision': 'Nuestra Visión',
    'about.values': 'Nuestros Valores',
    'about.team': 'Nuestro Equipo',
    'about.whyChooseUs': 'Por Qué Elegirnos',
    'about.experience': 'Años de Experiencia',
    'about.commitment': 'Compromiso con la Calidad',
    'about.customerService': 'Servicio al Cliente Excepcional',

    // Contact Page
    'contact.title': 'Contáctanos',
    'contact.getInTouch': 'Ponte en Contacto',
    'contact.visitUs': 'Visítanos',
    'contact.callUs': 'Llámanos',
    'contact.emailUs': 'Envíanos un Correo',
    'contact.businessHours': 'Horario de Atención',
    'contact.mondayFriday': 'Lunes - Viernes',
    'contact.saturday': 'Sábado',
    'contact.sunday': 'Domingo',
    'contact.closed': 'Cerrado',
    'contact.sendMessage': 'Enviar Mensaje',
    'contact.findUs': 'Encuéntranos',
    'contact.directions': 'Obtener Direcciones',

    // Sell Car Page
    'sellCar.title': 'Vende Tu Auto',
    'sellCar.description': 'Obtén el mejor valor por tu vehículo',
    'sellCar.vehicleInfo': 'Información del Vehículo',
    'sellCar.personalInfo': 'Información Personal',
    'sellCar.uploadPhotos': 'Subir Fotos',
    'sellCar.getQuote': 'Obtener Cotización',
    'sellCar.instantOffer': 'Obtén una Oferta Instantánea',
    'sellCar.fairPrice': 'Precio Justo de Mercado',
    'sellCar.quickProcess': 'Proceso Rápido y Fácil',

    // Login/Auth
    'auth.login': 'Iniciar Sesión',
    'auth.logout': 'Cerrar Sesión',
    'auth.register': 'Registrarse',
    'auth.forgotPassword': '¿Olvidaste tu Contraseña?',
    'auth.resetPassword': 'Restablecer Contraseña',
    'auth.emailAddress': 'Dirección de Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.rememberMe': 'Recuérdame',
    'auth.loginSuccess': '¡Inicio de sesión exitoso!',
    'auth.loginError': 'Correo electrónico o contraseña inválidos',
    'auth.logoutSuccess': 'Sesión cerrada exitosamente',
    'auth.unauthorized': 'Acceso no autorizado',

    // Errors
    'error.pageNotFound': 'Página No Encontrada',
    'error.somethingWentWrong': 'Algo Salió Mal',
    'error.tryAgain': 'Por Favor Intenta de Nuevo',
    'error.goHome': 'Ir a la Página Principal',
    'error.contactSupport': 'Contactar Soporte',

    // Success Messages
    'success.saved': 'Guardado exitosamente',
    'success.updated': 'Actualizado exitosamente',
    'success.deleted': 'Eliminado exitosamente',
    'success.sent': 'Enviado exitosamente',
    'success.booked': 'Reservado exitosamente',
    'success.cancelled': 'Cancelado exitosamente'
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Get language from localStorage or default to English
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'en';
  });

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};